import os
import io
import uvicorn
import docx
import pypdf
from typing import Optional
from fastapi import FastAPI, Form, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from agno.agent import Agent
from agno.models.google import Gemini
from dotenv import load_dotenv

# Load environment variables
load_dotenv(".env.local")

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def extract_text_from_file(file_bytes: bytes, filename: str) -> str:
    """Safely extracts raw text layout from PDF or DOCX binaries"""
    text = ""
    try:
        if filename.lower().endswith('.docx'):
            doc = docx.Document(io.BytesIO(file_bytes))
            text = "\n".join([para.text for para in doc.paragraphs])
        elif filename.lower().endswith('.pdf'):
            pdf_reader = pypdf.PdfReader(io.BytesIO(file_bytes))
            for page in pdf_reader.pages:
                text += page.extract_text() or ""
        else:
            text = file_bytes.decode('utf-8', errors='ignore')
    except Exception as e:
        print(f"Error parsing file content for {filename}: {e}")
    return text

@app.post("/api/dynamic-rag")
async def dynamic_rag_endpoint(
    message: str = Form("Summarize the attached document."),
    file: Optional[UploadFile] = File(None)
):
    print("--- BACKEND CONNECTED (FORCED GEMINI MODE) ---")
    document_context = ""
    print(f"Received request! Message: {message}")
    
    if file and file.filename:
        print(f"Received file upload stream: {file.filename}")
        try:
            file_bytes = await file.read()
            document_context = extract_text_from_file(file_bytes, file.filename)
            print(f"Extracted {len(document_context)} characters from document.")
        except Exception as file_err:
            print(f"Failed to read file: {file_err}")
        finally:
            await file.close()

        # Intercept if file was uploaded but no text could be extracted
        if not document_context.strip():
            print("Intercepted empty document context (likely a scanned PDF or image).")
            return {"response": "The uploaded PDF appears to be a scanned document or image-based file with no selectable text. Please upload a text-based document or copy-paste the text content directly."}

    try:
        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if not gemini_api_key:
            print("WARNING: GEMINI_API_KEY environment variable is not set.")
        
        gemini_model = Gemini(id="gemini-2.5-flash", api_key=gemini_api_key)
        print("Initialized Gemini model engine successfully.")
    except Exception as model_init_err:
        print(f"Failed to initialize Gemini engine directly: {model_init_err}")
        return {"response": "Model engine configuration error."}

    agent = Agent(
        model=gemini_model,
        markdown=True,
        description="You are an advanced AI assistant designed to extract information and summarize structural files.",
        instructions=[
            "Prioritize matching answers to text context segments appended inside the document block parameters.",
            "If summarizing, use neat Markdown headers, clean spacing, and structural bullet points."
        ]
    )

    final_prompt = f"User Request: {message}\n\n"
    if document_context:
        final_prompt += f"--- START OF ATTACHED DOCUMENT BACKGROUND context ---\n{document_context}\n--- END OF ATTACHED DOCUMENT BACKGROUND context ---"

    try:
        print("Running Agno Agent via Gemini...")
        response = agent.run(final_prompt)
        
        # Safe extraction of Agno response text content
        output_text = response.content if hasattr(response, 'content') else str(response)
        
        if output_text is None:
            output_text = "No response content generated by Agent."
            
        print(f"Agent response generated successfully: {output_text[:50]}...")
        
        return {"response": output_text}
    except Exception as agent_err:
        print(f"Agno Agent runtime error execution: {agent_err}")
        return {"response": f"Sorry, I ran into an operational issue processing the context: {str(agent_err)}"}

if __name__ == "__main__":
    print(f"Starting Agno Agent Service on port 8000...")
    uvicorn.run(app, host="0.0.0.0", port=8000)

